spring.datasource.url=jdbc:postgresql://localhost:5432/foodiedb_uat
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:secret}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.cache.type=redis
spring.data.redis.host=redis-uat
spring.data.redis.port=6379