# =====================
# H2 In-Memory (Dev)
# =====================
spring.datasource.url=jdbc:h2:mem:foodiedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

spring.main.lazy-initialization=false
spring.jpa.open-in-view=false
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.com.example.foodie=DEBUG
logging.level.org.springframework.web=DEBUG